# Generated by Django 2.2 on 2020-01-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('DOB', models.DateField(max_length=24)),
                ('qualification', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('reson_for_visit', models.TextField()),
            ],
        ),
    ]
